<a href="https://colab.research.google.com/github/rusha-rashq/PyTorch-Trials/blob/main/PyTorch_Trials.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [ ]:
# Tensors
my_list = [[1,2,3,4,5], [6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [5]:
np1 = np.random.rand(3,4)
np1

array([[0.86552313, 0.71893558, 0.16567847, 0.8033744 ],
       [0.18762965, 0.66470838, 0.26581607, 0.48520922],
       [0.87972868, 0.95196911, 0.20031627, 0.97384555]])

In [6]:
np1.dtype

dtype('float64')

In [7]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 0.4154,  0.7931,  0.8085,  0.3806],
        [-0.7998, -0.4808, -0.0065,  0.4100],
        [-0.4495, -0.3930, -1.1589,  1.1271]])

In [8]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [9]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.8655, 0.7189, 0.1657, 0.8034],
        [0.1876, 0.6647, 0.2658, 0.4852],
        [0.8797, 0.9520, 0.2003, 0.9738]], dtype=torch.float64)

In [2]:
# Tensor Operations
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# Reshape and View
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [4]:
# Reshape if we don't know the number of items using -1
my_torch2 = torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
my_torch2 = my_torch2.reshape(-1,5)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [6]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
my_torch4 = my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [8]:
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
my_torch6 = my_torch5.reshape(2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [10]:
my_torch5[1] = 777
my_torch5

tensor([  0, 777,   2,   3,   4,   5,   6,   7,   8,   9])

In [11]:
my_torch6

tensor([[  0, 777,   2,   3,   4],
        [  5,   6,   7,   8,   9]])

In [12]:
# Slices
my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
# Grab a specific item
my_torch7[7]

tensor(7)

In [14]:
# Grab slice
my_torch8 = my_torch7.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [15]:
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [16]:
# Return column
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])